# -*- coding: utf-8 -*-
"""ntsb_text_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z0SduWFdsuyHsm_o1rCUen3CrpZFFRyG

# NTSB 항공사고 보고서 텍스트 마이닝
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
import re

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from collections import Counter
from itertools import combinations

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.cluster import KMeans

import networkx as nx

from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from scipy import stats

nltk.download('stopwords')
nltk.download('wordnet')

"""## 2. 데이터 불러오기 및 전처리"""

file_path = 'data/ntsbexcel_new24.xlsx'
df = pd.read_excel(file_path)

df = df[['Accident Date', 'Accident Year', 'Wing Type', 'Processed Text']]
df.head()

tmp = df['Processed Text'].astype(str).str.lower()
tmp = tmp.apply(lambda x: re.sub(r'[^a-z\s]', '', x))

stop_words = set(stopwords.words('english'))
tmp = tmp.apply(lambda x: ' '.join([word for word in x.split() if word not in stop_words]))
tmp = tmp.apply(lambda x: ' '.join([word for word in x.split() if re.match(r'^[a-z]{3,}$', word)]))

ps = PorterStemmer()
lm = WordNetLemmatizer()

df_after = df[['Accident Date', 'Accident Year', 'Wing Type']].copy()
df_after['Processed Text'] = tmp.apply(lambda x: ' '.join([lm.lemmatize(word) for word in x.split()]))

df_after['Accident Date'] = pd.to_datetime(df_after['Accident Date'], format='%m/%d/%Y')
df_after = df_after.sort_values(by='Accident Date', ascending=True)

df_after.head()

fixed_wing = df_after[df_after['Wing Type'].astype(str).str.lower().str.contains('fixed', na=False)]
rotorcraft = df_after[df_after['Wing Type'].astype(str).str.lower().str.contains('rotor', na=False)]

fixed_wing.to_excel('fixed_wing_grouped.xlsx', index=False)
rotorcraft.to_excel('rotorcraft_grouped.xlsx', index=False)

print('fixed-wing:', fixed_wing.shape)
print('rotorcraft:', rotorcraft.shape)

"""## 3. 빈도 분석"""

vectorizer = CountVectorizer(max_features=30)
X = vectorizer.fit_transform(df_after['Processed Text'])

word_freq = dict(zip(vectorizer.get_feature_names_out(), X.toarray().sum(axis=0)))
top_keywords = sorted(word_freq.items(), key=lambda x: -x[1])[:30]

top_keywords

words = [w for w, c in top_keywords]
counts = [c for w, c in top_keywords]

plt.figure(figsize=(12, 6))
plt.barh(words[::-1], counts[::-1])
plt.title('Top 30 Word Frequency')
plt.xlabel('Frequency')
plt.ylabel('Word')
plt.show()

for wt in ['fixed-wing', 'rotorcraft']:
    sub = df_after[df_after['Wing Type'].astype(str).str.lower().str.contains(wt, na=False)]

    vectorizer = CountVectorizer(max_features=20)
    X = vectorizer.fit_transform(sub['Processed Text'])

    word_freq = dict(zip(vectorizer.get_feature_names_out(), X.toarray().sum(axis=0)))
    top_words = sorted(word_freq.items(), key=lambda x: -x[1])[:20]

    print(' ', wt)
    print(top_words)

    words = [w for w, c in top_words]
    counts = [c for w, c in top_words]

    plt.figure(figsize=(10, 5))
    plt.barh(words[::-1], counts[::-1])
    plt.title(f'Top 20 Most Frequent Words for Wing Type: {wt}')
    plt.xlabel('Frequency')
    plt.ylabel('Word')
    plt.show()

"""## 4. TF-IDF 키워드 네트워크"""

tfidf = TfidfVectorizer(min_df=2, max_features=30)
X = tfidf.fit_transform(df_after['Processed Text'])
keywords = tfidf.get_feature_names_out()

print('Top extracted keywords:')
print(keywords)

pair_counter = Counter()

for doc in df_after['Processed Text']:
    tokens = set(doc.split()) & set(keywords)
    for w1, w2 in combinations(sorted(tokens), 2):
        pair_counter[(w1, w2)] += 1

print('Top co-occurring keyword pairs:')
for (w1, w2), c in pair_counter.most_common(10):
    print(f'{w1} - {w2}: {c}')

G = nx.Graph()
freq = dict(zip(keywords, np.asarray(X.sum(axis=0)).flatten()))

for kw, f in freq.items():
    G.add_node(kw, size=f)

threshold = 500
for (w1, w2), c in pair_counter.items():
    if c >= threshold:
        G.add_edge(w1, w2, weight=c)

pos = nx.spring_layout(G, k=0.6, seed=42)
node_sizes = [G.nodes[n]['size'] * 0.3 for n in G.nodes]
edge_widths = [G[u][v]['weight'] / 800 for u, v in G.edges]

plt.figure(figsize=(14, 10))
nx.draw_networkx_nodes(G, pos, node_size=node_sizes, alpha=0.85)
nx.draw_networkx_edges(G, pos, width=edge_widths, alpha=0.4)
nx.draw_networkx_labels(G, pos, font_size=10, font_weight='bold')
plt.title('Aviation Accident Keyword Co-occurrence Network')
plt.axis('off')
plt.show()

"""## 5. LDA 토픽 모델링"""

cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
dtm = cv.fit_transform(df_after['Processed Text'])
feature_names = cv.get_feature_names_out()

lda = LatentDirichletAllocation(
    n_components=7,
    learning_method='online',
    random_state=42,
    max_iter=20,
    n_jobs=-1
)

lda.fit(dtm)

for idx, topic in enumerate(lda.components_):
    top_words = [feature_names[i] for i in topic.argsort()[-10:][::-1]]
    print(f'Topic {idx+1}: {", ".join(top_words)}')

"""## 6. STM"""

# !pip install tomotopy
import tomotopy as tp

ps = PorterStemmer()

model = tp.DMRModel(k=6, alpha=0.1, sigma=1.0, seed=42)

for _, row in df_after.iterrows():
    tokens = [ps.stem(w) for w in row['Processed Text'].split() if len(w) > 2]
    if len(tokens) > 5:
        model.add_doc(tokens, metadata=str(row['Wing Type']))

model.burn_in = 100
model.train(0)

print('Num docs:', len(model.docs))
print('Vocab size:', model.num_vocabs)
print('Num words:', model.num_words)

for i in range(0, 1000, 100):
    model.train(100)
    print('Iteration:', i, 'Log-likelihood:', model.ll_per_word)

print('STM Topics:')
for k in range(model.k):
    words = [w for w, p in model.get_topic_words(k, top_n=10)]
    print(f'Topic {k+1}: {", ".join(words)}')

"""## 7. BERTopic

실행 시간이 오래 걸릴 수 있다.
"""

# !pip install bertopic sentence-transformers umap-learn hdbscan

from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from umap import UMAP
from hdbscan import HDBSCAN

docs = df_after['Processed Text'].tolist()

embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', random_state=42)
hdbscan_model = HDBSCAN(min_cluster_size=15, metric='euclidean', cluster_selection_method='eom', prediction_data=True)
vectorizer_model = CountVectorizer(stop_words='english', min_df=2, ngram_range=(1, 2))

topic_model = BERTopic(
    embedding_model=embedding_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer_model,
    nr_topics=6,
    calculate_probabilities=False,
    verbose=True
)

topics, probs = topic_model.fit_transform(docs)

print(topic_model.get_topic_info())

print('BERTopic Topics:')
for tid in range(6):
    topic_words = topic_model.get_topic(tid)
    if topic_words:
        words = [w for w, p in topic_words[:10]]
        print(f'Topic {tid+1}: {", ".join(words)}')

"""## 8. 10년 단위 토픽 변화

10년씩 나눠 LDA와 BERTopic 결과를 대략 확인한다.
"""

df_after['Decade'] = (df_after['Accident Year'] // 10) * 10

decades = sorted(df_after['Decade'].dropna().unique())

decades

for decade in decades:
    sub = df_after[df_after['Decade'] == decade]
    print('=========================')
    print(int(decade), 's / docs:', len(sub))

    if len(sub) < 5:
        continue

    cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
    dtm = cv.fit_transform(sub['Processed Text'])
    names = cv.get_feature_names_out()

    lda_tmp = LatentDirichletAllocation(n_components=3, random_state=42, max_iter=10)
    lda_tmp.fit(dtm)

    for idx, topic in enumerate(lda_tmp.components_):
        top_words = [names[i] for i in topic.argsort()[-8:][::-1]]
        print(f'LDA topic {idx+1}: {", ".join(top_words)}')

# BERTopic도 같은 방식으로 decade별로 돌려볼 수 있다.

for decade in decades:
    sub = df_after[df_after['Decade'] == decade]
    print('=========================')
    print(int(decade), 's / docs:', len(sub))

    if len(sub) < 20:
        continue

    docs_decade = sub['Processed Text'].tolist()

    topic_model_decade = BERTopic(
        embedding_model=embedding_model,
        nr_topics=3,
        vectorizer_model=CountVectorizer(stop_words='english', min_df=2, ngram_range=(1, 2)),
        verbose=False
    )

    topics_decade, _ = topic_model_decade.fit_transform(docs_decade)
    print(topic_model_decade.get_topic_info().head())

"""## 9. 시계열 분석 - fixed wing"""

fixed = pd.read_excel('fixed_wing_grouped.xlsx')
df_fixed = pd.DataFrame(fixed)

df_fixed['date'] = pd.to_datetime(df_fixed['Accident Year'], format='%Y')
df_f = df_fixed.sort_values('date')
df_f.set_index('date', inplace=True)

yearly_data = df_f.resample('Y').agg({'Processed Text': ' '.join})
yearly_data['Processed Text'] = yearly_data['Processed Text'].fillna('')

yearly_data.head()

yearly_word_counts = {}

for date, row in yearly_data.iterrows():
    text = row['Processed Text']
    tokens = text.split()
    word_count = Counter(tokens)
    yearly_word_counts[date] = word_count

total_word_counts = Counter()
for wc in yearly_word_counts.values():
    total_word_counts.update(wc)

top_n = 10
top_words = [word for word, count in total_word_counts.most_common(top_n)]

print('상위 10개 단어:', top_words)

f_word_trends = pd.DataFrame(index=yearly_data.index)

for word in top_words:
    f_word_trends[word] = [yearly_word_counts[date].get(word, 0) for date in yearly_data.index]

f_word_trends.to_csv('f_word_trends.csv')
f_word_trends.head()

for word in f_word_trends.columns[:3]:
    plt.figure(figsize=(12, 4))
    plt.plot(f_word_trends.index, f_word_trends[word], label=word)
    plt.title('Top Words yearly Frequency Trends')
    plt.xlabel('Date')
    plt.ylabel('Frequency')
    plt.legend()
    plt.grid(True)
    plt.show()

correlation_matrix = f_word_trends[top_words].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix of Top Words')
plt.show()

threshold = 0.5
high_corr_pairs = []

for i in range(len(correlation_matrix.columns)):
    for j in range(i):
        if correlation_matrix.iloc[i, j] > threshold:
            high_corr_pairs.append((correlation_matrix.columns[i], correlation_matrix.columns[j], correlation_matrix.iloc[i, j]))

print('correlation threshold:', threshold)
for pair in high_corr_pairs:
    print(f'{pair[0]} - {pair[1]}: {pair[2]:.2f}')

f_cluster_data = f_word_trends[top_words].T

k = 4
kmeans = KMeans(n_clusters=k, random_state=0).fit(f_cluster_data)
cluster_labels = kmeans.labels_

for word, label in zip(top_words, cluster_labels):
    print(f'{word} cluster{label}')

for cluster in range(k):
    words_in_cluster = [word for word, label in zip(top_words, cluster_labels) if label == cluster]

    plt.figure(figsize=(12, 4))
    for word in words_in_cluster:
        plt.plot(f_word_trends.index, f_word_trends[word], label=word)
    plt.title(f'Cluster {cluster}')
    plt.legend()
    plt.grid(True)
    plt.show()

"""## 10. fixed wing - 정상성 확인 / 로그변환 / ARIMA"""

non_stationary_words = []

for word in f_word_trends.columns:
    series = f_word_trends[word]
    result = adfuller(series)
    p_value = result[1]

    if p_value > 0.05:
        non_stationary_words.append(word)
        print(f'{word}는 비정상 시계열 (p-value: {p_value:.4f}).')
    else:
        print(f'{word}는 정상 시계열 (p-value: {p_value:.4f}).')

df_diff = f_word_trends[non_stationary_words].diff().dropna()

for word in non_stationary_words:
    plt.figure(figsize=(12, 4))

    plt.subplot(1, 2, 1)
    plt.plot(f_word_trends[word], label=f'Original_{word}')
    plt.title(f'original_{word}')
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(df_diff[word], label=f'Differenced_{word}')
    plt.title(f'diff_{word}')
    plt.legend()

    plt.show()

# !pip install pmdarima
from pmdarima.arima import auto_arima

result_lst = []
tmp = []

for word in top_words:
    print('
단어:', word)

    ts = f_word_trends[word]
    ts_log = np.log(ts + 1)

    plt.figure(figsize=(12, 4))
    plt.plot(ts_log, label=f'{word} (Log Transformed)')
    plt.title(f"LOG_'{word}'")
    plt.xlabel('Date')
    plt.ylabel('Log(Frequency)')
    plt.legend()
    plt.grid(True)
    plt.show()

    result = adfuller(ts_log)
    print('ADF p-value:', result[1])

    if result[1] > 0.05:
        ts_log = ts_log.diff().dropna()

    tmp.append(ts_log)

arima_models = []

for i, ts_series in enumerate(tmp):
    word = top_words[i]
    print('
ARIMA:', word)

    plot_acf(ts_series, lags=20)
    plt.show()

    plot_pacf(ts_series, lags=20)
    plt.show()

    model = auto_arima(ts_series,
                       start_p=0, max_p=5,
                       start_q=0, max_q=5,
                       seasonal=False,
                       stepwise=True,
                       suppress_warnings=True,
                       error_action='ignore')

    print(model.summary())
    arima_models.append(model)

    residuals = pd.Series(model.resid(), index=ts_series.index[-len(model.resid()):])

    plt.figure(figsize=(12, 4))
    plt.plot(residuals)
    plt.title(f"'{word}' residual")
    plt.grid(True)
    plt.show()

    stats.probplot(residuals, dist='norm', plot=plt)
    plt.title(f"'{word}' residual Q-Q plot")
    plt.show()

forecast_result = []

for i, model in enumerate(arima_models[:5]):
    word = top_words[i]
    ts_series = tmp[i]

    n_periods = 5
    forecast, conf_int = model.predict(n_periods=n_periods, return_conf_int=True)

    last_date = ts_series.index[-1]
    future_dates = pd.date_range(start=last_date + pd.DateOffset(years=1), periods=n_periods, freq='Y')

    forecast_original = np.exp(forecast) - 1
    lower_95 = np.exp(conf_int[:, 0]) - 1
    upper_95 = np.exp(conf_int[:, 1]) - 1

    forecast_df = pd.DataFrame({
        'date': future_dates,
        'word': word,
        'forecast': forecast_original,
        'lower_95': lower_95,
        'upper_95': upper_95
    })
    forecast_result.append(forecast_df)

    plt.figure(figsize=(12, 5))
    plt.plot(ts_series.index, ts_series, label='Data')
    plt.plot(future_dates, forecast, linestyle='--', label='Forecast')
    plt.fill_between(future_dates, conf_int[:, 0], conf_int[:, 1], alpha=0.2, label='95% Confidence Interval')
    plt.title(f"Time Series Forecast for '{word}' (5 Years)")
    plt.xlabel('Year')
    plt.ylabel('Log(Frequency)')
    plt.legend()
    plt.grid(True)
    plt.show()

f_forecast = pd.concat(forecast_result)
f_forecast.to_csv('fixed_wing_forecast.csv', index=False)
f_forecast.head()

"""## 11. 시계열 분석 - rotorcraft"""

rotated = pd.read_excel('rotorcraft_grouped.xlsx')
df_rotated = pd.DataFrame(rotated)

df_rotated['date'] = pd.to_datetime(df_rotated['Accident Year'], format='%Y')
df_r = df_rotated.sort_values('date')
df_r.set_index('date', inplace=True)

yearly_data = df_r.resample('Y').agg({'Processed Text': ' '.join})
yearly_data['Processed Text'] = yearly_data['Processed Text'].fillna('')

yearly_word_counts = {}

for date, row in yearly_data.iterrows():
    text = row['Processed Text']
    tokens = text.split()
    word_count = Counter(tokens)
    yearly_word_counts[date] = word_count

total_word_counts = Counter()
for wc in yearly_word_counts.values():
    total_word_counts.update(wc)

top_n = 10
r_top_words = [word for word, count in total_word_counts.most_common(top_n)]

print('상위 10개 단어:', r_top_words)

r_word_trends = pd.DataFrame(index=yearly_data.index)

for word in r_top_words:
    r_word_trends[word] = [yearly_word_counts[date].get(word, 0) for date in yearly_data.index]

r_word_trends.to_csv('r_word_trends.csv')
r_word_trends.head()

for word in r_word_trends.columns[:3]:
    plt.figure(figsize=(12, 4))
    plt.plot(r_word_trends.index, r_word_trends[word], label=word)
    plt.title('Top Words yearly Frequency Trends')
    plt.xlabel('Date')
    plt.ylabel('Frequency')
    plt.legend()
    plt.grid(True)
    plt.show()

correlation_matrix = r_word_trends[r_top_words].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix of Top Words')
plt.show()

threshold = 0.5
high_corr_pairs = []

for i in range(len(correlation_matrix.columns)):
    for j in range(i):
        if correlation_matrix.iloc[i, j] > threshold:
            high_corr_pairs.append((correlation_matrix.columns[i], correlation_matrix.columns[j], correlation_matrix.iloc[i, j]))

print('correlation threshold:', threshold)
for pair in high_corr_pairs:
    print(f'{pair[0]} - {pair[1]}: {pair[2]:.2f}')

r_cluster_data = r_word_trends[r_top_words].T

k = 3
kmeans = KMeans(n_clusters=k, random_state=0).fit(r_cluster_data)
cluster_labels = kmeans.labels_

for word, label in zip(r_top_words, cluster_labels):
    print(f'{word} cluster{label}')

for cluster in range(k):
    words_in_cluster = [word for word, label in zip(r_top_words, cluster_labels) if label == cluster]

    plt.figure(figsize=(12, 4))
    for word in words_in_cluster:
        plt.plot(r_word_trends.index, r_word_trends[word], label=word)
    plt.title(f'Cluster {cluster}')
    plt.legend()
    plt.grid(True)
    plt.show()

"""## 12. rotorcraft - 정상성 확인 / ARIMA"""

non_stationary_words = []

for word in r_word_trends.columns:
    series = r_word_trends[word]
    result = adfuller(series)
    p_value = result[1]

    if p_value > 0.05:
        non_stationary_words.append(word)
        print(f'{word}는 비정상 시계열 (p-value: {p_value:.4f}).')
    else:
        print(f'{word}는 정상 시계열 (p-value: {p_value:.4f}).')

df_diff = r_word_trends[non_stationary_words].diff().dropna()

for word in non_stationary_words:
    plt.figure(figsize=(12, 4))

    plt.subplot(1, 2, 1)
    plt.plot(r_word_trends[word], label=f'Original_{word}')
    plt.title(f'original_{word}')
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(df_diff[word], label=f'Differenced_{word}')
    plt.title(f'diff_{word}')
    plt.legend()

    plt.show()

r_tmp = []

for word in r_top_words:
    print('단어:', word)

    ts = r_word_trends[word]
    ts_log = np.log(ts + 1)

    result = adfuller(ts_log)
    print('ADF p-value:', result[1])

    if result[1] > 0.05:
        ts_log = ts_log.diff().dropna()

    r_tmp.append(ts_log)

r_arima_models = []

for i, ts_series in enumerate(r_tmp):
    word = r_top_words[i]
    print('ARIMA:', word)

    plot_acf(ts_series, lags=20)
    plt.show()

    plot_pacf(ts_series, lags=20)
    plt.show()

    model = auto_arima(ts_series,
                       start_p=0, max_p=5,
                       start_q=0, max_q=5,
                       seasonal=False,
                       stepwise=True,
                       suppress_warnings=True,
                       error_action='ignore')

    print(model.summary())
    r_arima_models.append(model)

    residuals = pd.Series(model.resid(), index=ts_series.index[-len(model.resid()):])

    plt.figure(figsize=(12, 4))
    plt.plot(residuals)
    plt.title(f"'{word}' residual")
    plt.grid(True)
    plt.show()

    stats.probplot(residuals, dist='norm', plot=plt)
    plt.title(f"'{word}' residual Q-Q plot")
    plt.show()

forecast_result = []

for i, model in enumerate(r_arima_models[:5]):
    word = r_top_words[i]
    ts_series = r_tmp[i]

    n_periods = 5
    forecast, conf_int = model.predict(n_periods=n_periods, return_conf_int=True)

    last_date = ts_series.index[-1]
    future_dates = pd.date_range(start=last_date + pd.DateOffset(years=1), periods=n_periods, freq='Y')

    forecast_original = np.exp(forecast) - 1
    lower_95 = np.exp(conf_int[:, 0]) - 1
    upper_95 = np.exp(conf_int[:, 1]) - 1

    forecast_df = pd.DataFrame({
        'date': future_dates,
        'word': word,
        'forecast': forecast_original,
        'lower_95': lower_95,
        'upper_95': upper_95
    })
    forecast_result.append(forecast_df)

    plt.figure(figsize=(12, 5))
    plt.plot(ts_series.index, ts_series, label='Data')
    plt.plot(future_dates, forecast, linestyle='--', label='Forecast')
    plt.fill_between(future_dates, conf_int[:, 0], conf_int[:, 1], alpha=0.2, label='95% Confidence Interval')
    plt.title(f"Time Series Forecast for '{word}' (5 Years)")
    plt.xlabel('Year')
    plt.ylabel('Log(Frequency)')
    plt.legend()
    plt.grid(True)
    plt.show()

r_forecast = pd.concat(forecast_result)
r_forecast.to_csv('rotorcraft_forecast.csv', index=False)
r_forecast.head()